### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by nohwnd** [gsakkas/gruvbox-mix#1]
It would be great if you added screenshots to your githubpage and vscode marketplace so it is possible to immediately see how the theme looks like. I installed it anyway but a lot of others may skip it because they don't want to pollute their editor with plugins they might not use.

**Comment by gsakkas** [comment]
I'm planning to add some screenshots the following days for that exact reason. Thanks!

**Comment by nohwnd** [comment]
Well do it rather sooner than later. Currently you are in the recently added list on marketplace, so it is easy to discover your theme.

**Comment by gsakkas** [comment]
Just uploaded some screenshots. Thanks for the heads up!

**Comment by nohwnd** [comment]
Looks great :)
